---
apiVersion: v1
kind: Service
metadata:
  name: testing7
  namespace: team1
  labels:
    app: testing7
    service: testing7
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: testing7